// Generated by CoffeeScript 1.7.1
(function() {
  var a, b;

  a = "a";

  b = "b";


  /*
   *  -----------------
   *  this is a multi-
   *  line comment
   *  will be shown in the output .js file
   *  -----------------
   */


  /*
    -----------------
    this is a multi-
    line comment
    leading "#" is not necessary
    -----------------
   */

}).call(this);
